### PR TITLE
Readme updated.

### PR DESCRIPTION
**Pull request by SayantaniDeb**
# Welcome, to my personal portfolio page.
issues
Forks
Stars
connect
          

## Table of contents

* [Technolgies used](#the-technologies-used-are)
* [Website-Images](#images)
* [Website-link](https://programmergaurav.github.io/)

## The technologies used are: 

* HTML
* SCSS
* JavaScript

## Images

| Content        | Snapshot           | 
| ------------- |:-------------:| 
| Home page      | image | 
| About      | image | 
| Skills | image |   
| Work |  image |
| Activity chart | image |
| Contact | image |

#26

### CODE REVIEW

**Comment by SayantaniDeb** [comment]
incase you decide to merge please add the hacktoberfest label to the PR

**Comment by ProgrammerGaurav** [comment]
looks good thanks, will merge after reviewing in some time

**Comment by SayantaniDeb** [comment]
Thank you!

**Comment by SayantaniDeb** [comment]
Please kindly merge the PR within 14 days or it will be invalid @ProgrammerGaurav

**Pull request merged**
